export * from './Home/index'
export * from './Annotaciya/index'
export * from './Panler-bazasi/Index'

export * from './7-Klass/Teoriya/index'
export * from './7-Klass/Joybar/index'
export * from './7-Klass/Laboratoriya/index'
export * from './7-Klass/Maseller-sheshiw/index'
export * from './7-Klass/Shınıǵıwları/index'

export * from './8-Klass/Teoriya/index'
export * from './8-Klass/Joybar/index'
export * from './8-Klass/Laboratoriya/index'
export * from './8-Klass/Maseller-sheshiw/index'
export * from './8-Klass/Shınıǵıwları/index'

export * from './9-Klass/Teoriya/index'
export * from './9-Klass/Joybar/index'
export * from './9-Klass/Laboratoriya/index'
export * from './9-Klass/Maseller-sheshiw/index'
export * from './9-Klass/Shınıǵıwları/index'

export * from './10-Klass/Teoriya/index'
export * from './10-Klass/Joybar/index'
export * from './10-Klass/Laboratoriya/index'
export * from './10-Klass/Maseller-sheshiw/index'
export * from './10-Klass/Shınıǵıwları/index'

export * from './11-Klass/Teoriya/index'
export * from './11-Klass/Joybar/index'
export * from './11-Klass/Laboratoriya/index'
export * from './11-Klass/Maseller-sheshiw/index'
export * from './11-Klass/Shınıǵıwları/index'